### ISSUE TITLE
Support agent host defined functions

### ISSUE THREAD

**Issue by binji** [bterlson/eshost#39]
The `agent` [host defined functions](https://github.com/tc39/test262/blob/master/INTERPRETING.md#host-defined-functions) don't seem to be implemented in any of the runtimes.

As a result some of the SharedArrayBuffer/Atomic tests can't run, nor the litmus tests (see https://github.com/tc39/test262/issues/1147).

**Comment by bterlson** [comment]
Indeed. I was hoping to get to this after modules. Thanks for reminding me, I should try to land the modules branch this weekend.

**Comment by rwaldron** [comment]
@bterlson I just briefed @nomadtechie on this work and we toured the agent code in https://github.com/mozilla/gecko-dev/blob/master/js/src/tests/test262-host.js 

@nomadtechie will be working on implementing agents for as many platforms as possible (with the goal of at least one, because that's reasonable)

**Comment by bterlson** [comment]
@rwaldron @nomadtechie this is excellent news! Please reach out if you need help :)

**Comment by rwaldron** [comment]
Completed
